apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/home/happyxhw/nfs/data"
    server: "172.16.12.188"

---

# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: mypvc1
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Mi